language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

cache:
  directories:
  - $HOME/.composer/cache/files

services:
  - mysql

before_script:
  - mysql -e 'create database elkarte;'
  - composer install

script: phpunit

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
